### ISSUE TITLE
How to add color background for inputBox Decoration ?

### ISSUE THREAD

**Issue by ismailxebia** [TinoGuo/pin_input_text_field#1]

**Comment by TinoGuo** [comment]
Until 0.0.1 you can not set background. But I think you can set background outside inputBox Decoration such as Container when you use underlineDecoration. I think this is a feature.

**Comment by TinoGuo** [comment]
@ismailxebia In addition, I hope you post the design draft what you want.

**Comment by TinoGuo** [comment]
It has completed with release 0.1.0
