### ISSUE TITLE
最新1.0.1无法显示

### ISSUE THREAD

**Issue by charlesYun** [TinoGuo/pin_input_text_field#10]
![image](https://user-images.githubusercontent.com/15682437/62007629-84991300-b182-11e9-8e93-104ded25efc9.png)
键盘事件有响应，但是输入内容看不到

**Comment by caoyunxiao** [comment]
嵌套在Column 里面的情况

**Comment by charlesYun** [comment]
嵌套在SizeBox里面的时候

**Comment by TinoGuo** [comment]
没有发生你说的那种情况，你是不是sizebox的大小为0，建议你inspector查看下元素是否存在

**Comment by charlesYun** [comment]
没有， 指定了宽高的。我改了下代码 把光标显示出来，发现都聚集在中间，不是分散在方框内

**Comment by charlesYun** [comment]
我反复尝试了，不嵌套 SizeBox 确实就没有这个问题

**Comment by TinoGuo** [comment]
可以用最简单的代码复现下这个问题吗？谢谢。

**Comment by suurqin** [comment]
我模拟器能显示没反应

**Comment by charlesYun** [comment]
![image](https://user-images.githubusercontent.com/15682437/62050872-b8d50800-b244-11e9-993d-0a8c7ae72b25.png)
![image](https://user-images.githubusercontent.com/15682437/62050875-bb376200-b244-11e9-8ffd-0f52d947d11d.png)
![image](https://user-images.githubusercontent.com/15682437/62050877-bd99bc00-b244-11e9-8a56-98c1d3d85034.png)

**Comment by TinoGuo** [comment]
根据你的这个代码，我还是没有复现出这个结果😂

**Comment by charlesYun** [comment]
。。。。这个就尴尬了，我下面还套了Column 和 row  不知道你那边是怎样的，我用的时候确实出现了这个问题。尝试解决失败后，换别的方案了

**Comment by TinoGuo** [comment]
我是把demo上的PinInputTextField直接改的，你要不发下`flutter doctor -v`的信息

**Comment by FaverSoar** [comment]
我用的是android9.0机器，我也遇到了同样的问题，输入内容无法显示。

**Comment by TinoGuo** [comment]
@FaverSoar 能提供下更详细的信息吗？只是无法显示我没办法定位修复。谢谢。

**Comment by williamsim** [comment]
怎么解决这个BUG？压根不显示输入内容

**Comment by TinoGuo** [comment]
试下2.0.0版本吧，你们没有详细信息提供，我只能自己测试了。

**Comment by TinoGuo** [comment]
@caoyunxiao @suurqin @FaverSoar @williamsim

**Comment by TinoGuo** [comment]
No response
