### ISSUE TITLE
能不能支持从剪贴板粘贴验证码

### ISSUE THREAD

**Issue by Niushimeng** [TinoGuo/pin_input_text_field#12]
我看代码中现在是直接禁止掉了，能否增加一个参数控制是否允许粘贴

**Comment by TinoGuo** [comment]
目前是禁止的，因为没有单独的开关来打开粘贴这个选项。如果开启的话还会把选中也打开，这样长按就会出现空白的选中条，你可以自己尝试一下。
目前有几个解决方案

1. 增加一个按钮来粘贴
2. 如果不介意我之前说的，可以fork本项目，修改`enableInteractiveSelection`重新打包
3. 如果你有好的什么解决方案来单独控制粘贴，可以pull request，我会合并进项目

**Comment by TinoGuo** [comment]
Long-time no response
