### ISSUE TITLE
FormField variation for the PinInputTextField

### ISSUE THREAD

**Issue by alyyasser** [TinoGuo/pin_input_text_field#13]
IMO, it would be good to have the FormField variation, which can add support for `validator`, and `onSaved`, also `validate()`, and `save()` method from `GlobalKey.currentState`

**Comment by TinoGuo** [comment]
It's really good advice, would you like to pull request?

**Comment by alyyasser** [comment]
well, i'll try, since i need it for my current project. will do the PR once it's done

**Comment by TinoGuo** [comment]
Perfect

**Comment by alyyasser** [comment]
it turns out i need to modify the Decorations implementation too, to be able to render the error message (validation result), is it okay for you?

**Comment by TinoGuo** [comment]
Sure, but it is optional not required.

**Comment by TinoGuo** [comment]
I have published a new version [2.0.1](https://pub.dev/packages/pin_input_text_field)
