### ISSUE TITLE
FormField's value not updated when TextEditingController not supplied

### ISSUE THREAD

**Issue by alyyasser** [TinoGuo/pin_input_text_field#18]
there's strange issue when creating `PinInputTextFormField` without supplying `TextEditingController` in constructor parameter. when using `TextEditingController` from inside `_PinInputTextFormFieldState`, it'll not update the `value`, that `value` will be used in `validator`, `onSave`, and other callback in `PinInputTextFormField`.

after investigating the logic i implemented before, it turns out i did it wrong (sorry). will land the PR to fix it soon. i've done the fix in my local repo.

**Comment by TinoGuo** [comment]
Thanks for your contribution. Don't feel guilty, you're pretty good.
