### ISSUE TITLE
Set pin code from code

### ISSUE THREAD

**Issue by jaumard** [TinoGuo/pin_input_text_field#2]
I'm working on a plugin to autofill sms code, I want to use your widget as textField but for now it doesn't support setting a pin from code. Would it be possible to add this ? 

I can do a PR if you don't have time but I want to be sure you'll accept it first :) 

Thanks !

**Comment by TinoGuo** [comment]
@jaumard code means abcd?  Supporting other input styles of Pin is coming. I think it will publish before the weekend.

**Comment by jaumard** [comment]
No I mean I want something like:
```
PinInputTextField(
              onSubmit: (pin) {
                //Add submit action.
              },
              currentCode: '123456',
              pinLength: 6,     // The length of the pin
              decoration: BoxTightDecoration(), // or BoxLooseDecoration, UnderlineDecoration
              width: 300.0,
              height: 48.0,
            );
```
That will allow to retrieve the PIN from the SMS and set it automatically on the field :) my widget will wrap this one and provide the PIN.

**Comment by TinoGuo** [comment]
@jaumard Okay, this feature will include next release.😃😃

**Comment by jaumard** [comment]
awesome ! Thanks @TinoGuo !

**Comment by TinoGuo** [comment]
@jaumard It's ready in dev branch

**Comment by jaumard** [comment]
thanks I'll try to test it today and let you know :)

**Comment by jaumard** [comment]
It works ! Just one thing, I find it really hard to find out when the field has the focus or not, would it be possible to add a focusColor under PinDecoration ? like this when the field has focus it put the first empty digit as the one with the focus, or if all are filled the last one. What do you think ?

**Comment by jaumard** [comment]
https://github.com/jaumard/sms_autofill :) when you've publish all of this I'll be all good to publish mine too ! Thanks !

**Comment by TinoGuo** [comment]
@jaumard It has been published just now!

**Comment by jaumard** [comment]
@TinoGuo thanks !! Perfect :)
