### ISSUE TITLE
如何设置每个node的输入框的高度及背景属性? 

### ISSUE THREAD

**Issue by DennisJu007** [TinoGuo/pin_input_text_field#22]
1、如何设置整体输入框的高度
2、如何随着每次输入更新已输入node的solidColor,因为enteredColor只能更新node的边框颜色属性

**Comment by TinoGuo** [comment]
@DennisJu007 
1. 可以在外部嵌套一个SizedBox或者Container
2. 后续版本增加支持

**Comment by DennisJu007** [comment]
1、好的，我试一下
2、收到
