### ISSUE TITLE
请问下，能把一句话中某些位置设置成带边框的吗？

### ISSUE THREAD

**Issue by xdnice** [TinoGuo/pin_input_text_field#26]
请问下，能把一句话中某些位置设置成带边框的，这些地方还很能输入字符，类似学习强国APP中填空题的效果吗？

**Comment by TinoGuo** [comment]
可以发一下效果图吗？没用过这个软件

**Comment by xdnice** [comment]
看看图片上传

**Comment by xdnice** [comment]
![123](https://user-images.githubusercontent.com/3805045/76934070-68bcca00-6929-11ea-998c-fac86b601491.jpg)
看看图片上传

**Comment by TinoGuo** [comment]
@xdnice 可以使用自定义绘制，继承下BoxLooseDecoration
