### ISSUE TITLE
Copy Paste Support

### ISSUE THREAD

**Issue by mocodesmo** [TinoGuo/pin_input_text_field#34]
Hello,

Usually for textfields, users require a long press to select the text and paste,
I am having a hard time implementing this with pin_input_text_field. 

Is there a way to implement this?

Thank you for your time.

**Comment by TinoGuo** [comment]
@mocodesmo Hi, I can support it but with some limitations due to the implementation of this lib. 
1. use TextField internal implementation, but the edit menu would offset unexpectedly
2. use external implementation, it could be customized

**Comment by TinoGuo** [comment]
implemented since 3.0.3
