### ISSUE TITLE
how to change background for inputs in UnderlineDecoration?

### ISSUE THREAD

**Issue by exuvia-dev** [TinoGuo/pin_input_text_field#36]
is there a prop about changing background color for UnderlineDecoration? I want to make something like this 
![image](https://user-images.githubusercontent.com/19880334/86219266-9e10bf00-bb8a-11ea-8a9c-467687aadb74.png)
I tried to make it with BoxLooseDecoration and solid color, but I can't change border to make it only on bottom.

**Comment by TinoGuo** [comment]
you can use `solidColor` since **3.0.4**, because this lib initial purpose only for pin and i ignored the `underlineDecoration`. anyway, you can use it now.
