### ISSUE TITLE
Paste support

### ISSUE THREAD

**Issue by jaumard** [TinoGuo/pin_input_text_field#38]
Would be nice if it was possible to paste the OTP code copied from messages.

**Comment by TinoGuo** [comment]
Hi, the lib support copy, cut & paste from 3.0.3.

**Comment by jaumard** [comment]
Any idea what can cause it not to work ? Because I use the last version and I don't have any copy/paste feature on my PinInputTextField

**Comment by jaumard** [comment]
I'm using it on my package https://github.com/jaumard/sms_autofill and I don't have any copy paste available

**Comment by jaumard** [comment]
never mind I just find out it's not enabled by default `enableInteractiveSelection` need to be set to true. 
Thanks!
