### ISSUE TITLE
输入框不会自动到键盘上方

### ISSUE THREAD

**Issue by IvanYue** [TinoGuo/pin_input_text_field#40]
输入框会被键盘挡住

**Comment by IvanYue** [comment]
希望可以优化，谢谢😊

**Comment by TinoGuo** [comment]
![untitled](https://user-images.githubusercontent.com/4519784/90948855-7ac10c80-e475-11ea-9923-fc7e7c398332.gif)
是可以自动滚动的哦, 请包裹一个ListView之类的滚动容器或者是否配置有问题
