### ISSUE TITLE
Add the capability to change the color of the text field after a value is entered into it.

### ISSUE THREAD

**Issue by nimi0112** [TinoGuo/pin_input_text_field#44]
Add the capability to change the color of the text field after a value is entered into it.

<img width="287" alt="91434490-7c7a3e00-e882-11ea-8023-0125389e12ab" src="https://user-images.githubusercontent.com/16234261/91709091-df7c1580-eb9f-11ea-95df-d0171a594770.png">

Right now we cannot change the background color after the value is entered in it.

**Comment by TinoGuo** [comment]
The feature is available since 3.1.0

**Comment by nimi0112** [comment]
Thank you @TinoGuo
