### ISSUE TITLE
Compile error for List.empty()

### ISSUE THREAD

**Issue by gokcer** [TinoGuo/pin_input_text_field#46]
At Commit b0ae7ae247671e31ba4381d631f146d85448739e lib/src/decoration/pin_decoration.dart line 29 creates compile error.

List.empty() create error at compiling for flutter 1.17.4 dart 2.8.4.

**Comment by VikasPawar2112** [comment]
> At Commit [b0ae7ae](https://github.com/TinoGuo/pin_input_text_field/commit/b0ae7ae247671e31ba4381d631f146d85448739e) lib/src/decoration/pin_decoration.dart line 29 creates compile error.
> 
> List.empty() create error at compiling for flutter 1.17.4 dart 2.8.4.

I am also getting this issue when build app.
Error log: pin_input_text_field-3.1.0/lib/src/decoration/pin_decoration.dart:29:44: Error: Method not found: 'List.empty'.
  List<double> get getGapWidthList => List.empty();

Details:
sms_autofill: ^1.2.5
Flutter 1.17.5 
Dart 2.8.4

**Comment by TinoGuo** [comment]
@gokcer @VikasPawar2112 i think it should be fixed it since 3.1.1 as no environment to verify.
