### ISSUE TITLE
ShowCursor property

### ISSUE THREAD

**Issue by dbondarchuk** [TinoGuo/pin_input_text_field#50]
For desktop platforms, showCursor property is needed.
This should be configurable the same way as other TextField properties.

**Comment by Vadaski** [comment]
agree

**Comment by TinoGuo** [comment]
#25 duplicate, would try to figure out the approach.

**Comment by lironiz** [comment]
I don't see the cursor on my mobile too. is it possible to show the cursor?

**Comment by TinoGuo** [comment]
@lironiz Hey, in this lib implementation, the cursor is hidden. I'm surprised that you folks are expected to have this feature.
I will try to implement by end of this year.

**Comment by TinoGuo** [comment]
It's implemented since 3.2.0, can refer #56
