### ISSUE TITLE
Fails while compling project

### ISSUE THREAD

**Issue by sourav-classklap** [TinoGuo/pin_input_text_field#54]
fails at pin_input_widget fails at line no. 489 textStyle: decoration.textStyle ?? themeData.textTheme.headline5, unable to find headline5 with existing flutter version
<img width="1440" alt="Screenshot 2020-12-01 at 16 08 10" src="https://user-images.githubusercontent.com/60959242/100729953-6cc54500-33ef-11eb-9ec0-c50b00b704e3.png">

**Comment by TinoGuo** [comment]
@sourav-classklap can i know which flutter version you used? can u post the flutter doctor output?

**Comment by TinoGuo** [comment]
No more response, closed. If any question regarding compile can refer the this repo actions
https://github.com/TinoGuo/pin_input_text_field/actions
