### ISSUE TITLE
Migrating to null safety

### ISSUE THREAD

**Issue by hayashi-ay** [TinoGuo/pin_input_text_field#61]
ref: https://dart.dev/null-safety/migration-guide

**Comment by TinoGuo** [comment]
Hey @hayashi-ay, the null-safety is not release until now, even we can release it but only with alpha. I don't have plan for it in near feature unless it's released. but it's welcome to push any PR❤️

**Comment by TinoGuo** [comment]
Release 4.0.0-nullsafety.0 for beta
