### ISSUE TITLE
3.1.1 upgrade to 3.3.0 crash

### ISSUE THREAD

**Issue by DennisJu007** [TinoGuo/pin_input_text_field#62]
i got this log, how can i fix it, thanks.
../../../Library/Android/flutter/.pub-cache/hosted/pub.flutter-io.cn/pin_input_text_field-3.3.0/lib/src/widget/pin_widget.dart:402:5: Error: Type 'AutovalidateMode' not found.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
../../../Library/Android/flutter/.pub-cache/hosted/pub.flutter-io.cn/pin_input_text_field-3.3.0/lib/src/widget/pin_widget.dart:402:5: Error: 'AutovalidateMode' isn't a type.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
    ^^^^^^^^^^^^^^^^
../../../Library/Android/flutter/.pub-cache/hosted/pub.flutter-io.cn/pin_input_text_field-3.3.0/lib/src/widget/pin_widget.dart:402:41: Error: Getter not found: 'AutovalidateMode'.
    AutovalidateMode autovalidateMode = AutovalidateMode.disabled,
                                        ^^^^^^^^^^^^^^^^
../../../Library/Android/flutter/.pub-cache/hosted/pub.flutter-io.cn/pin_input_text_field-3.3.0/lib/src/widget/pin_widget.dart:436:13: Error: No named parameter with the name 'autovalidateMode'.
            autovalidateMode: autovalidateMode,
            ^^^^^^^^^^^^^^^^

**Comment by TinoGuo** [comment]
@DennisJu007 can u attach the result of `flutter doctor -v`?

**Comment by DennisJu007** [comment]
> @DennisJu007 can u attach the result of `flutter doctor -v`?

thanks for replying, i fixed it by upgrade flutter SDK
