### ISSUE TITLE
Feature: add parameter to change border radius in CirclePinDecoration

### ISSUE THREAD

**Issue by danielmessi13** [TinoGuo/pin_input_text_field#78]

**Comment by danielmessi13** [comment]
Forget it, I already solved it using BoxLooseDecoration, decoration example images are not loading in readme XD

<img width="439" alt="image" src="https://user-images.githubusercontent.com/29608634/202538220-1716120c-2fb6-4377-a8e2-39cbb32770a1.png">

**Comment by TinoGuo** [comment]
maybe it's huge gif :)
