### ISSUE TITLE
Error: No named parameter with the name 'toolbarOptions'.

### ISSUE THREAD

**Issue by astraube** [TinoGuo/pin_input_text_field#84]
Please, I would like a version compatibility parameter.

You removed the "toolbarOptions" parameter from the "PinInputTextField" class, and it started giving errors in thousands of projects.

Error: No named parameter with the name 'toolbarOptions'.
      toolbarOptions: ToolbarOptions(paste: true),

**Comment by TinoGuo** [comment]
Hi, thx for raising it. I will release a new version to support old version soon. Pls be patient. Thx

**Comment by manishkummar21** [comment]
Guys, Update these issue even we are facing

**Comment by TinoGuo** [comment]
Revert the removal in 4.4.0
