### ISSUE TITLE
'EditableTextContextMenuBuilder' not found in pin_widget.dart

### ISSUE THREAD

**Issue by rishabhsharma3617** [TinoGuo/pin_input_text_field#88]
One of our app modules is using the package as transitive dependency v - 4.4.0 , the app kept on failing due to this error coming from inside this package 
Error log - 

` Error: Type 'EditableTextContextMenuBuilder' not found.
pin_widget.dart:65
  final EditableTextContextMenuBuilder? contextMenuBuilder;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
: Error: Type 'EditableTextContextMenuBuilder' not found.
pin_widget.dart:419
    EditableTextContextMenuBuilder? contextMenuBuilder,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

: Error: 'EditableTextContextMenuBuilder' isn't a type.
pin_widget.dart:65
  final EditableTextContextMenuBuilder? contextMenuBuilder;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

: Error: No named parameter with the name 'contextMenuBuilder'.
pin_widget.dart:281
        contextMenuBuilder: widget.contextMenuBuilder,
        ^^^^^^^^^^^^^^^^^^
: Context: Found this candidate, but the arguments don't match.
text_field.dart:277
  const TextField({
        ^^^^^^^^^
: Error: 'EditableTextContextMenuBuilder' isn't a type.
pin_widget.dart:419
    EditableTextContextMenuBuilder? contextMenuBuilder,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2`
Upon looking in pub cache the EditableTextContextMenuBuilder is also coming as not defined in this package , can we look into the same !

**Comment by rishabhsharma3617** [comment]
cc - @TinoGuo

**Comment by bh-oussama** [comment]
Same issue with 4.3.0. Last version working well is 4.2.0, just tested that now.

**Comment by TinoGuo** [comment]
sorry, but pls stay at 4.2.0 coz the `EditableTextContextMenuBuilder` required flutter 3.7
https://dart.dev/tools/pub/versioning#version-constraints-the-dart-approach to constraint the this library in 4.2.0
will soon (maybe this weekend) rollout 4.5.0 to adopt flutter 3.7 and 4.4.1 to support below flutter 3.7

**Comment by TinoGuo** [comment]
pls use 4.4.1 to resolve the issue, it should work coz it passed the 3.3.10 [github action](https://github.com/TinoGuo/pin_input_text_field/actions/runs/4215738933)

**Comment by rishabhsharma3617** [comment]
Thanks @TinoGuo for resolving this _/\_ . This is the package which i was using https://pub.dev/packages/sms_autofill and it was using the your package internally . ^ ^

**Comment by TinoGuo** [comment]
> Thanks @TinoGuo for resolving this _/_ . This is the package which i was using https://pub.dev/packages/sms_autofill and it was using the your package internally . ^ ^

welcome
