### ISSUE TITLE
Adjust the space between boxes.

### ISSUE THREAD

**Issue by taiseiiiii** [TinoGuo/pin_input_text_field#96]
Hello.

Thank you for Providing useful package

Currently the space between input boxes can't be adjusted
Is there any way to adjust these margin?

**Comment by TinoGuo** [comment]
Hi @taiseiiiii , it do support margin between box as long as it implement SupportGap interface.
- UnderlineDecoration
- BoxLooseDecoration
- BoxTightDecoration
- CirclePinDecoration
all above 4 support, u need to override getGapWidth or getGapWidthList to make the change
